# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: true
cache: packages
dist: trusty

before_install:
- sudo rm -vf /etc/apt/sources.list.d/*riak*
- sudo apt-get update

after_success:
  - Rscript -e 'covr::codecov()'
